version: '3'

services:
  pmtool:
    image: openmrsinfra/pmtool
    ports:
      - ${PMTOOL_PORT-80}:3000
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 10s
      timeout: 3s
