version: '2.1'

services:
  oclmsp:
    image: openconceptlab/oclmsp:staging
    environment:
      - OCL_DOMAIN=${OCL_DOMAIN:-staging.openconceptlab.org}
      - ENVIRONMENT=${ENVIRONMENT:-staging}
    ports:
      - 8084:80
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-q", "http://localhost/"]
