version: '3'

services:
  mongo-plir:
    restart: "always"
    container_name: openhim-mongo-plir
    image: mongo:3.4
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: "exit 0"

  backup:
    image: openmrsinfra/cron-backup:latest
    depends_on:
      - mongo-plir
    volumes:
      - mongodb_data:/mongodb-data
      - ${BACKUP_DIR-./backups}:/backup
    environment:
      - DIRS=/mongodb-data:plir_openmhinm_data
      - SCHEDULE=0 0 * * *
    restart: always
    healthcheck:
      test: "exit 0"
    
  core-plir:
    restart: "always"
    container_name: openhim-core-plir
    image: jembi/openhim-core:latest
    environment:
      - mongo_url=mongodb://mongo-plir/openhim
      - mongo_atnaUrl=mongodb://mongo-plir/openhim
    volumes:
      - /etc/letsencrypt/live/namanga.openmrs.org/ :/etc/letsencrypt/live/namanga.openmrs.org/
      - ./core-config.json:/usr/src/app/config/default.json  
    ports:
      - "5555:5001"
      - "8093:8080"
    healthcheck:
      test: "exit 0"   
    depends_on:
      - mongo-plir
  
  console-plir:
    restart: "always"
    container_name: openhim-console-plir
    image: jembi/openhim-console:latest
    ports:
        - "9000:80"  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      timeout: 20s    
    volumes:
      - ./default.json:/usr/share/nginx/html/config/default.json
    
volumes:
  mongodb_data:
    driver: local
