version: "3"
services:
  plir-hapi:
    image: mozzy11/openmrs-plir:basic_auth
    container_name: plir_hapi_auth
    restart: on-failure
    ports:
      - "8080:8080"
  plir-mysql:
    image: mysql:latest
    container_name: plir-mysql-auth
    restart: always
    environment:
      MYSQL_DATABASE: 'hapi'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    volumes:
      - hapi-fhir-mysql:/var/lib/mysql
volumes:
  hapi-fhir-mysql:
