version: "3"
services:
  plir-hapi:
    image: mozzy11/openmrs-plir:basic_auth
    container_name: plir_hapi_auth
    restart: always
    ports:
      - "8091:8080"
    healthcheck:
      test: "exit 0"
