version: "3.7"

services:
  app:
    image: openmrsinfra/shields:latest
    restart: "always"
    ports:
      - "8083:3033"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      timeout: 5s
